version: "3.8"

services:

  jenkins:
    image: jenkins/jenkins
    ports:
    - "127.0.0.1:9080:8080"
    volumes:
    - "$HOME/volumes/jenkins:/var/jenkins_home"
    - "$HOME/.ssh:/home/jenkins/.ssh"
    restart: unless-stopped

  devCon:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: "/usr/sbin/sshd -D && su sshuser"
    image: ubuntu:local
    ports:
      - "127.0.0.1:2022:22"

volumes:
  jenkins:
